language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock 
  - conda activate test-environment
  - conda build packaging/  # add directory if needed.
  - conda install your-package --use-local

script:
  - pytest -v --color=yes --cov=cpr tests

after success:
  - conda install codecov
  - codecov

