language: generic

jobs:
  include:
    - os: linux
      env: TOXENV=3.6
    - os: linux
      env: TOXENV=3.7
    - os: linux
      env: TOXENV=3.8
    - os: osx
      env: TOXENV=3.6
    - os: osx
      env: TOXENV=3.7
    - os: osx
      env: TOXENV=3.8
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge 
#  - conda install conda-build=3.19.2
  - conda create -q -n test-environment python=$TOXENV conda pytest six pytest-cov pytest-mock 
  - conda activate test-environment
  - pwd
  - echo $HOME 
  - cd tests/test_data
  - wget https://github.com/00krishna-tools/nyuki/releases/download/v0.0.1/sample_image_small.tif
  - cd $HOME
#  - conda build packaging/  # add directory if needed.
#  - conda install --use-local nyuki

script:
  - pytest -v --color=yes --cov=cpr tests

after success:
  - conda install codecov
  - codecov

