# With infos from
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
# https://packaging.python.org/en/latest/appveyor/
# https://github.com/rmcgibbo/python-appveyor-conda-example

environment:
  matrix:

    - PYTHON_VERSION: "3.6"
      MINICONDA: C:\Miniconda36-x64
      ENV_FILE: "ci/travis/36-latest-conda-forge.yaml"

    - PYTHON_VERSION: "3.7"
      MINICONDA: C:\Miniconda37-x64
      ENV_FILE: "ci/travis/37-latest-conda-forge.yaml"

    - PYTHON_VERSION: "3.8"
      MINICONDA: C:\Miniconda37-x64
      ENV_FILE: "ci/travis/38-latest-conda-forge.yaml"

# all our python builds have to happen in tests_script...
build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - CALL "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update conda
  - conda info -a
  - conda config --add channels conda-forge
  - "conda create -n test-environment python=%PYTHON_VERSION% conda pytest six pytest-cov pytest-mock"
  - "conda activate test-environment"
  - conda install --yes --file requirements_conda.txt
  - pip install -r requirements.txt
  - python setup.py install

test_script:
  - conda list
  - pytest tests

