{% set name = "nyuki" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/00krishna-tools/nyuki/archive/v{{ version }}.tar.gz
  sha256: f98b3d43bdc89fe4d10dfe5da59d9e961013329df7d799396195b31cf15f84ed

build:
  noarch: python
  number: 0
  entry_points:
    - nyuki = nyuki.nyuki:nyuki

requirements:
  host:
    - python >3.5
    - pip
    - numpy >=1.18.5
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - pillow
    - libwebp
    - libtiff >4.0
  run:
    - python >3.5
    - numpy >=1.18.5
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - pillow
    - libwebp
    - libtiff >4.0

test:
  imports:
    - nyuki
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [not win]
    - test -f ${PREFIX}/lib/libtiff{{ SHLIB_EXT }}  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx{{ SHLIB_EXT }}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1  # [win]

about:
  home: https://github.com/00krishna-tools/nyuki
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A geospatial library for humans. "

  description: "Nyuki: a geospatial library for humans"
  doc_url: https://nyuki-a-geospatial-toolkit-for-humans.readthedocs.io/en/latest/
  dev_url: https://github.com/00krishna-tools/nyuki

extra:
  recipe-maintainers:
    - 00krishna
