package:
  name: nyuki
  version: "v0.0.1"

source:
  url: https://github.com/00krishna-tools/nyuki

build:
  noarch: python
  number: 1
  string: testRelease
  skip: true  # [win and py27]
  entry_points:
    - nyuki = nyuki.src.nyuki:nyuki

requirements:
  build:
    - git

  host:
    - python
    - pip
    - numpy >=1.18.5
    - pandas >=1.0.5
    - rasterio >=1.1.0
    - click >=6
    - tqdm
    - geopandas >=0.8.1
    - Pillow

  run:
    - python
    - numpy >=1.18.5
    - pandas >= 1.0.5
    - rasterio >=1.1.0
    - click >=6
    - tqdm
    - geopandas >=0.8.1
    - Pillow
    - enum34  # [py<34]

test:
  requires:
    - pip
  files:
  imports:
    - nyuki
  commands:

about:
  home: https://github.com/00krishna-tools/nyuki
  license: MIT
  license_file: LICENSE.txt
  summary: Nyuki is a geospatial toolkit that creates human readable interfaces to complex geospatial libraries.

extra:
  recipe-maintainers:
    - 00krishna