
{% set name = "nyuki" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  url: https://github.com/00krishna-tools/nyuki/archive/v{{ version }}.tar.gz
  sha256: a6c48cba1dd9149c976e0e505e54a39031736fb4fd9c7eacfc6799a6d7c461db

build:
  noarch: python
  number: 0
  entry_points:
    - nyuki = nyuki.nyuki:nyuki

requirements:
  host:
    - python >3.5
    - pip
    - numpy >=1.18.5
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - pillow
    - libwebp
  run:
    - python >3.5
    - numpy >=1.18.5
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - pillow
    - libwebp

test:
  imports:
    - nyuki

about:
  home: https://github.com/00krishna-tools/nyuki
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A geospatial library for humans. "

  description: "Nyuki: a geospatial library for humans"
  doc_url: https://nyuki-a-geospatial-toolkit-for-humans.readthedocs.io/en/latest/
  dev_url: https://github.com/00krishna-tools/nyuki

extra:
  recipe-maintainers:
    - 00krishna
