package:
  name: nyuki
  version: "v0.0.1"

source:
  git_url: https://github.com/00krishna-tools/nyuki

build:
  number: 1
  string: testRelease
  entry_points:
    - nyuki = src.nyuki:nyuki

requirements:
  build:
    - git
    - python {{ python }}

  host:
    - python {{ python }}
    - pip
    - numpy >=1.18.5
    - pytest-runner
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - Pillow
    - libwebp
#    - gdal=2.4.4

  run:
    - python {{ python }}
    - numpy >=1.18.5
    - pandas
    - rasterio
    - click >=7
    - tqdm
    - geopandas
    - Pillow
    - libwebp
    - enum34  # [py<34]
#    - gdal=2.4.4

test:
  requires:
#    - pip
  files:
  imports:
#    - nyuki
  commands:

about:
  home: https://github.com/00krishna-tools/nyuki
  license: MIT
  license_file: LICENSE.txt
  summary: Nyuki is a geospatial toolkit that creates human readable interfaces to complex geospatial libraries.

extra:
  recipe-maintainers:
    - 00krishna
