{% set version = "v0.0.1" %}

package:
  name: nyuki
  version: {{ version }}

source:
  url: https://github.com/00krishna-tools/nyuki/archive/{{ version }}.tar.gz
  sha1: fcb8ca94e13b340405bef7464e687409934043a4
build:
  number: 1
  string: testRelease
  skip: true  # [win and py27]
  entry_points:
    - nyuki = nyuki.src.nyuki:nyuki
  osx_is_app: True
requirements:
    - git
  host:
    - python
    - pip
    - numpy
    - pandas
    - rasterio
    - click >=6
    - contextlib
    - os
    - sys
    - tqdm
    - geopandas
    - Pillow

  run:
    - python
    - numpy
    - pandas
    - rasterio
    - click >=6
    - contextlib
    - os
    - sys
    - tqdm
    - geopandas
    - Pillow
    - enum34  # [py<34]

test:
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython >=2.0
  files:
  imports:
    - nyuki
  commands:

about:
  home: https://github.com/00krishna-tools/nyuki
  license: MIT
  license_file: LICENSE.txt
  summary: Nyuki is a geospatial toolkit that creates human readable interfaces to complex geospatial libraries.

extra:
  recipe-maintainers:
    - 00krishna

